source "http://rubygems.org"
gem "sinatra", ">=1.1.2"
gem "json", ">=1.4.6"
gem "dm-core", ">=1.0.2"
gem "dm-validations", ">=1.0.2"
gem "dm-timestamps", ">=1.0.2"
gem "dm-migrations", ">=1.0.2"
gem "dm-postgres-adapter", ">=1.0.2"
gem "dm-sqlite-adapter", ">=1.0.2"